### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by jochi44** [hofff/contao-googleanalytics#4]
contao version: 4.13.5
app version: 1.5.1
php version: 8.1.7

When upgrading the php version to 8.1.7, the following error is shown in the error.log of the server:

`PHP message: PHP Warning:  Undefined global variable $googleanalytics_included in /var/www/web/vendor/hofff/contao-googleanalytics/src/Hofff/Contao/Frontend/GoogleAnalytics.php on line 25"`

**Comment by frontendschlampe** [comment]
We're working on a new version and hope to finish it within the next weeks.

**Comment by cliffparnitzky** [comment]
Gefixt mit #3
